### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by AndriiUhryn** [BysahaOleh/slush-react-boilerplate#1]
Following next steps I got an error.

Steps to reproduce:

sudo npm i -g slush slush-react-boilerplate
mkdir test_slush_project
cd test_slush_project
slush react-boilerplate

Error:

Error: Cannot find module 'git-origin-url'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/uhryn_andrii/.nvm/versions/node/v9.2.1/lib/node_modules/slush-react-boilerplate/questions/prompts/main.js:2:16)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)

**Comment by BysahaOleh** [comment]
@AndriiUhryn I fixed it in 0.1.3 version.
